### ISSUE TITLE
SharedMemory breaks if data contains null byte (\x00)

### ISSUE THREAD

**Issue by Paulsson99** [MO-RISE/pycluon#17]
I am trying to share an image between several programs using the SharedMemory class. I noticed that only about half of my image was transfered and then the rest of it was completely black. When investigating closer I noticed that the break always happened at places with a blue color (0, 0, 255). 

When I started digging into the source code I noticed this line.
https://github.com/MO-RISE/pycluon/blob/171b9696e48ebedf18811aefee6fe77ad9bed892/src/pycluon.cpp#L193
Here the data is converted to a NULL terminated string and I assume this is why my data is cut off. 

I confirmed this by changing my blue color to (1, 1, 255) instead and now my image is complete on the receiving end. 

I assume this is a bug and that it should be changed in future versions?

Code to replicate the error:
~~~python
from pycluon import SharedMemory
import numpy as np

# Create image with one element equal to 0
img = np.ones((480, 640, 3), dtype=np.uint8)
img[240, 320, 0] = 0

sm = SharedMemory("img.rgb", img.size)

sm.lock()
sm.data = img.tobytes()
assert sm.data == img.tobytes() # Fails but should pass
sm.unlock()
~~~

**Comment by freol35241** [comment]
Thanks for a nice and well-structured issue report. Yes, this definitely sounds like a bug.

Feel free to propose a PR that solves this!

I, unfortunately, will not have time to work on this for the foreseeable future.

**Comment by freol35241** [comment]
@Paulsson99 Turned out to be a really quick fix. Version 0.2.3 is soon available.

**Comment by Paulsson99** [comment]
Oh great! Thanks for the quick fix @freol35241!
